#pragma once

#include <stdint.h>

typedef enum {
    HCI_PKT_COMMAND = 0x01,
    HCI_PKT_ACL     = 0x02,
    HCI_PKT_SCO     = 0x03,
    HCI_PKT_EVENT   = 0x04,
} hci_packet_type_t;

#define HCI_CMD_MAX_LEN 260u
#define HCI_EVENT_MAX_LEN 260u
#ifndef HCI_ACL_MAX_LEN
#define HCI_ACL_MAX_LEN 2048u
#endif

#define HCI_OPCODE(ogf, ocf) ((uint16_t)((((uint16_t)(ogf)) << 10u) | ((ocf) & 0x03ffu)))
#define HCI_OPCODE_RESET HCI_OPCODE(0x03u, 0x0003u)
#define HCI_OPCODE_READ_LOCAL_VERSION HCI_OPCODE(0x04u, 0x0001u)
#define HCI_OPCODE_READ_LOCAL_EXTENDED_FEATURES HCI_OPCODE(0x04u, 0x0004u)
#define HCI_OPCODE_READ_BD_ADDR HCI_OPCODE(0x04u, 0x0009u)
#define HCI_OPCODE_SET_EVENT_MASK HCI_OPCODE(0x03u, 0x0001u)
#define HCI_OPCODE_LE_SET_EVENT_MASK HCI_OPCODE(0x08u, 0x0001u)
#define HCI_OPCODE_LE_SET_RANDOM_ADDRESS HCI_OPCODE(0x08u, 0x0005u)
#define HCI_OPCODE_LE_SET_SCAN_PARAMETERS HCI_OPCODE(0x08u, 0x000bu)
#define HCI_OPCODE_LE_SET_SCAN_ENABLE HCI_OPCODE(0x08u, 0x000cu)
#define HCI_OPCODE_LE_CREATE_CONNECTION HCI_OPCODE(0x08u, 0x000du)
#define HCI_OPCODE_LE_EXTENDED_CREATE_CONNECTION HCI_OPCODE(0x08u, 0x0043u)
#define HCI_OPCODE_WRITE_SCAN_ENABLE HCI_OPCODE(0x03u, 0x001au)
#define HCI_OPCODE_WRITE_SIMPLE_PAIRING_MODE HCI_OPCODE(0x03u, 0x0056u)

#define HCI_EVENT_COMMAND_COMPLETE 0x0eu
#define HCI_EVENT_COMMAND_STATUS 0x0fu
#define HCI_EVENT_VENDOR_SPECIFIC 0xffu
#define HCI_EVENT_CONNECTION_COMPLETE 0x03u
#define HCI_EVENT_CONNECTION_REQUEST 0x04u
#define HCI_EVENT_LE_META 0x3eu
#define HCI_SUBEVENT_LE_CONNECTION_COMPLETE 0x01u
#define HCI_SUBEVENT_LE_ADVERTISING_REPORT 0x02u
#define HCI_SUBEVENT_LE_ENHANCED_CONNECTION_COMPLETE 0x0au
#define HCI_SUBEVENT_LE_DIRECTED_ADVERTISING_REPORT 0x0bu
#define HCI_SUBEVENT_LE_EXTENDED_ADVERTISING_REPORT 0x0du
